apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    kubernetes.io/bootstrapping: wardle-defaults
  name: wardler
rules:
- apiGroups:
  - wardle.k8s.io
  resources:
  - flunders
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch