apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.sample.k8s.io
spec:
  insecureSkipTLSVerify: true
  group: sample.k8s.io
  priority: 200
  service:
    name: sample-api
    namespace: kube-system
  version: v1alpha1
