apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sample-apiserver
  namespace: kube-system
  labels:
    apiserver: "true"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: sample-apiserver
        apiserver: "true"
    spec:
      containers:
      - name: sample-apiserver
        image: gcr.io/wfender-gke-dev/k8s-aggregator-sample-apiserver-amd64:bcb1b7e-dirty
        imagePullPolicy: IfNotPresent
        args:
        - "--etcd-servers=http://localhost:2379"
        - "--requestheader-client-ca-file=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
        - "--audit-log-path=-"
        - "--audit-log-maxage=0"
        - "--audit-log-maxbackup=0"
      - name: etcd
        image: quay.io/coreos/etcd:v3.0.17
